from typing import Final

DEFAULT_CONFIDENCE: Final = 0.5
DEFAULT_IOU_THRESHOLD: Final = 0.5
DEFAULT_IOU_WITH_MIN: Final = False
DEFAULT_MAX_RESULTS: Final = 0
DEFAULT_TOP_N: Final = 1
DEFAULT_USE_NMS: Final = True

# Audio
DEFAULT_AUDIO_SAMPLE_RATE: Final = 16000
DEFAULT_AUDIO_CHANNELS: Final = 1
DEFAULT_CHUNK_AUDIO_DURATION: Final = 0.625
DEFAULT_MAX_AUDIO_DURATION: Final = 10.0
DEFAULT_MIN_AUDIO_DURATION: Final = 0.1
DEFAULT_SILENCE_DURATION: Final = 0.1
DEFAULT_SILENCE_THRESHOLD: Final = 10
DEFAULT_USE_VAD: Final = True

# Mel Spectrogram
DEFAULT_MEL_AXIS_ORDER: Final = "time_first"
DEFAULT_MEL_INPUT_FORMAT: Final = "nchw"
DEFAULT_MEL_LOG: Final = True
