name: Build synap-python pip wheel as artefact

on: [workflow_dispatch]

permissions:
  packages: write
  contents: write

jobs:
  build-aarch64:
    runs-on: ubuntu-latest
    env:
      DIST_DIR: ${{ github.workspace }}/dist

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install build
        
      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels
          path: ${{ env.DIST_DIR }}