name: Build synap-python pip wheel for draft release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag of the draft release to upload to'
        required: true

permissions:
    packages: write
    contents: write

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
        
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install build
        
      - name: Build wheel
        run: |
          python -m build --wheel
        
      - name: Get wheel file name
        run: |
          WHEEL_FILE=$(ls dist/*.whl)
          if [ -z "$WHEEL_FILE" ]; then
            echo "No wheel file found"
            exit 1
          fi
          echo "WHEEL_FILE=$(basename $WHEEL_FILE)" >> $GITHUB_ENV

      - name: Upload wheel as asset
        run: |
          gh release upload ${{ github.event.inputs.tag_name }} \
            dist/${{ env.WHEEL_FILE }} \
              --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}